name         'puppet-module-sudoers'
version      '1.2.3'
source       'ssh://gerrit.ericsson.se:29418/puppet/puppet-module-sudoers'
author       'Ericsson'
license      'Apache License, Version 2.0'
summary      'Manages sudoers from PUA data'
description  'Manages sudoers file(s) from PUA data'
project_page 'https://gerrit.ericsson.se/#/admin/projects/puppet/puppet-module-sudoers'

dependency 'puppetlabs/stdlib', '>= 3.2.0 < 5.0.0'
dependency 'juliengk/stdlibplus', '>= 0.1.0'
